# Generated by Django 5.0.4 on 2024-05-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='is_destacada',
            field=models.BooleanField(default=False),
        ),
    ]
