# Generated by Django 5.0.4 on 2024-04-28 21:55

import Comisaria.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comisaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('grupo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='InformeDelictivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to=Comisaria.models.informeDelictivoPath)),
                ('fecha', models.DateField()),
                ('comisaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comisaria.comisaria')),
            ],
        ),
        migrations.CreateModel(
            name='MapaDelito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to=Comisaria.models.mapaDelitoPath)),
                ('fecha', models.DateField()),
                ('comisaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comisaria.comisaria')),
            ],
        ),
        migrations.CreateModel(
            name='MapaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to=Comisaria.models.mapaRiesgoPath)),
                ('fecha', models.DateField()),
                ('comisaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comisaria.comisaria')),
            ],
        ),
    ]
